source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PlayerView_Example' do
  pod 'PlayerView', :path => '../'
end

target 'PlayerView_Tests' do
  pod 'PlayerView', :path => '../'

  
end
